repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: ["--fix"]
        language: system
      - id: ruff-format
        language: system
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        additional_dependencies: ["click<9"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: envkeep-tests
        name: envkeep-tests
        entry: bash -lc 'pytest'
        language: system
        pass_filenames: false
